/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.9).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Correos;
import io.swagger.model.PostRsType;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-11-07T06:35:27.605Z")

@Api(value = "mailsend", description = "the mailsend API")
public interface MailsendApi {

    @ApiOperation(value = "Enviar un Correo", nickname = "enviarCorreo", notes = "", response = PostRsType.class, tags={ "MailSend", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "EXITO", response = PostRsType.class),
        @ApiResponse(code = 400, message = "Bad request", response = PostRsType.class),
        @ApiResponse(code = 404, message = "Not found", response = PostRsType.class) })
    @RequestMapping(value = "/mailsend/correo",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<PostRsType> enviarCorreo(@ApiParam(value = "Cabecera estándar" ,required=true) @RequestHeader(value="headerRq", required=true) String headerRq,@ApiParam(value = "servIdKallsony" ,required=true) @RequestHeader(value="serviceID", required=true) String serviceID,@ApiParam(value = "Informacion del correo a enviar" ,required=true )  @Valid @RequestBody Correos correo);

}
